"""Add comments table

Revision ID: 72c15fceedff
Revises: 08c81b7f16f7
Create Date: 2026-08-24 02:48:44.505258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72c15fceedff'
down_revision: Union[str, Sequence[str], None] = '08c81b7f16f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.add_column('payments', sa.Column('files', sa.JSON(), nullable=True))
    op.add_column('reports', sa.Column('files', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('files', sa.JSON(), nullable=True))
    op.add_column('workers', sa.Column('files', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'files')
    op.drop_column('tasks', 'files')
    op.drop_column('reports', 'files')
    op.drop_column('payments', 'files')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.alter_column('expenses', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
