"""Add files and fix schema

Revision ID: 81bb77f08997
Revises: 38d3b6f014ba
Create Date: 2026-08-24 02:25:15.655915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81bb77f08997'
down_revision: Union[str, Sequence[str], None] = '38d3b6f014ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('files', sa.JSON(), nullable=True))
    
    
    op.add_column('payments', sa.Column('files', sa.JSON(), nullable=True))
    op.add_column('reports', sa.Column('files', sa.JSON(), nullable=True))
    op.add_column('workers', sa.Column('files', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'files')
    op.drop_column('reports', 'files')
    op.drop_column('payments', 'files')
    
    
    op.drop_column('candidates', 'files')
    # ### end Alembic commands ###
