"""add invite_token

Revision ID: b5106983e91a
Revises: 72c15fceedff
Create Date: 2026-09-20 19:24:02.718968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5106983e91a'
down_revision: Union[str, Sequence[str], None] = '72c15fceedff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'experience',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('candidates', 'english_level',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('candidates', 'desired_income',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('shift_reports', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('shift_reports', sa.Column('worker_amount', sa.Float(), nullable=True))
    op.add_column('shift_reports', sa.Column('admin_amount', sa.Float(), nullable=True))
    op.add_column('shift_reports', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('shift_reports', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('shift_reports', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('shift_reports', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('shift_reports', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'PENDING'"))
    op.create_index(op.f('ix_shift_reports_id'), 'shift_reports', ['id'], unique=False)
    op.create_foreign_key(None, 'shift_reports', 'users', ['worker_id'], ['id'])
    op.add_column('telegram_accounts', sa.Column('assigned_worker_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'telegram_accounts', 'users', ['assigned_worker_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telegram_accounts', type_='foreignkey')
    op.drop_column('telegram_accounts', 'assigned_worker_id')
    op.drop_constraint(None, 'shift_reports', type_='foreignkey')
    op.drop_index(op.f('ix_shift_reports_id'), table_name='shift_reports')
    op.alter_column('shift_reports', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'PENDING'"))
    op.alter_column('shift_reports', 'amount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('shift_reports', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('shift_reports', 'deleted_at')
    op.drop_column('shift_reports', 'is_deleted')
    op.drop_column('shift_reports', 'admin_amount')
    op.drop_column('shift_reports', 'worker_amount')
    op.drop_column('shift_reports', 'notes')
    op.alter_column('candidates', 'desired_income',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('candidates', 'english_level',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('candidates', 'experience',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
